### ISSUE TITLE
Support no symbols and length

### ISSUE THREAD

**Issue by pigmonkey** [roddhjav/pass-update#1]
It would be nice if `pass-update` could accept the same password options as `pass generate` -- specifically `-n`/`--no-symbols` and the length.

Looking for `-n` and passing it on to `cmd_generate` seems simple enough. Taking length as the final argument the way `pass generate` does may be tricky since `pass-update` accepts multiple entries. Maybe just accept `-l`/`--length`?

    $ pass update -n -l 128 social/facebook social/github

**Comment by roddhjav** [comment]
Does c761955 fit your wish ?

It is a fast solution for now, major update for pass-update will come later with automatic update (see branch `auto`)

**Comment by pigmonkey** [comment]
Yup, that looks like it will work. Thanks!
