### ISSUE TITLE
Add ability to skip certain password modification?

### ISSUE THREAD

**Issue by jakubtopic** [roddhjav/pass-update#12]
For my use case it would be nice to have a possibility to decide whether to edit a password or skip it and continue with others. However, current behaviour is that if you answer 'No' to the question `Are you ready to provide/generate a new password? [y/N]`, the script exits with status `1`.

**Comment by roddhjav** [comment]
Hi, This is a good proposition. Merged.

**Comment by jakubtopic** [comment]
Happy to help!
