### ISSUE TITLE
install: mkdir /usr/lib/password-store: Operation not permitted

### ISSUE THREAD

**Issue by sflands** [roddhjav/pass-update#14]
Ran with sudo make install as instructed, but it fails. Installed pass via homebrew.

**Comment by roddhjav** [comment]
Hi, if you look at the [install](https://github.com/roddhjav/pass-update#installation) paragraph, you will see that for OSX you need to run the following:
```
make install PREFIX=/usr/local
```

**Comment by sflands** [comment]
Wow, not sure how I missed that... thanks!
