### ISSUE TITLE
Change passwords that match a regular expression

### ISSUE THREAD

**Issue by duckbrain** [roddhjav/pass-update#15]
Before using `pass` some users may have been using a formula for their passwords. It would be great if we could have the extension search for passwords that match a regular expression, so we can find and replace those with non-generated passwords.

**Comment by roddhjav** [comment]
Hi,
So you would like something like an `--exclude` option that don't update if it match a reg expression.

I like the proposition. I will implement it in the future. But allow a bit of time, I do not have the time at the moment. I also plan a full rewrite of the extension in python with a lot of new features, this `exclude` feature will be part of this re-write.

**Comment by duckbrain** [comment]
I was actually thinking the opposite. An `--include` option, so say I used to make my passwords with a pattern like below mixed in with my generated passwords since I started using `pass`. I could search for passwords I need to update to randomly generated passwords.

```
facebookMy~SecurePassword1!
googleMySecurePassword1! # Some websites don't allow '~'
twitterMy~SecurePassword1. # Some '!'
dmvSecu. # Why does the DMV only allow 8 chars?
```

No problem on time. Sounds good!

**Comment by roddhjav** [comment]
This is now implement with both the `--include` and `--exclude` options

**Comment by duckbrain** [comment]
Thanks, this works great!
