### ISSUE TITLE
Merge upstream

### ISSUE THREAD

**Issue by seanfarley** [roddhjav/pass-update#17]
Just a random question if you think it'd make sense to merge this into pass proper (instead of an extension)? It seems to me that this should be a core feature of pass.

**Comment by roddhjav** [comment]
Hi,

This is not possible. The main purpose of *pass* is to provide a light password manager with the minimal core feature. This is not my choice but Jason's choice. He does not want to add extra features that would at term make pass heavy and hard to review and maintain.

On the contrary, the purpose of this extension is to provide as many ways as possible to allow users to update their password easily. Which mean for instance: I might re-write it in python and it *will* became bigger than pass itself.

**Comment by seanfarley** [comment]
Gotcha; I am new to pass and was worried it had some design choices I was unaware of. Thanks for the explanation!
