### ISSUE TITLE
Farnetic on the syntax to set the length of updated passwords

### ISSUE THREAD

**Issue by webdeploy-davoli-alessio** [roddhjav/pass-update#23]
Should'nt the syntax for setting the length of the new password follow the one used with the command `generate`? 

So like: `pass generate Email/jasondonenfeld.com 15`

I know it's a bit a useless, but i think it's more intuitive!

**Comment by roddhjav** [comment]
Instead of pass generate with pass update you can give more than one passname to update. Therefore, it is more intuitive to use the `-l` option to give the password length.
