### ISSUE TITLE
apt-key deprecated

### ISSUE THREAD

**Issue by hucste** [roddhjav/pass-update#27]
On your README file, about Debian/*Buntu (like), you wroted about:
`wget URL | sudo apt-key…"` instruction 

Since Debian 11, using apt-key is deprecated; on Ubuntu, it's more oldier… since 2020.
Officially, this tool will be deleted on Debian 12, and Ubuntu 22.04.
_(see `man 8 apt-key`)_

Please, wrote more:
For Debian 11:
```
curl -fsSL https://pkg.pujol.io/debian/gpgkey | gpg --dearmor | sudo tee "/etc/apt/trusted.gpg.d/roddhjav.gpg" > /dev/null
```
More simple with wget:
```
wget -qO- https://pkg.pujol.io/debian/gpgkey | sudo tee /etc/apt/trusted.gpg.d/roddhjav.gpg
```
_(or `roddhjav.asc` if the key is armored)_

---

On Debian > 11, and Ubuntu ≥ 22.04 Jammy, /etc/apt/keyrings is provided as the recommended location for keys not managed by packages.
This will be: 
```
wget -qO- https://pkg.pujol.io/debian/gpgkey | sudo tee /etc/apt/keyrings/roddhjav.gpg
```

---

Egual, share a file sources, as roddhjav.sources, segun the [deb822-style format](https://manpages.debian.org/bullseye/dpkg-dev/deb822.5.en.html#simple):
```
Types: deb
URIs: https://pkg.pujol.io/debian/repo
Suites: all
Architectures: amd64
Components: main
Signed-By: /etc/apt/trusted.gpg.d/roddhjav.gpg
```
 _(or /etc/apt/keyrings/roddhjav.gpg for Ubuntu ≥ 22.04, Debian > 11)_

And share-it too. ;)
```
wget -qO- https://pkg.pujol.io/debian/roaddhjav.sources | sudo tee /etc/apt/sources.list.d/roddhjav.sources
```

---

To finish: `sudo apt update && sudo apt install pass-extension-update`

**Comment by roddhjav** [comment]
Thanks for the reminder. Fixed.
