### ISSUE TITLE
[Feature request] Automatically match password length

### ISSUE THREAD

**Issue by NicolaSmaniotto** [roddhjav/pass-update#28]
I let `pass` generate passwords of the default length, which at the moment is 25 characters.
Some websites (example: [poste.it](https://www.poste.it)) enforce a maximum length (16 characters) for the password, and it's hard to remember what it is for each one.
It would be useful for this extension to match the previous password's length if no explicit `-l` is provided.
This would allow users to satisfy the site requirements when creating the account, and then have the extension automatically create valid passwords while updating.

**Comment by roddhjav** [comment]
This is now implemented. It needs to be enabled using the new `-a` option. See [3fc36d8](https://github.com/roddhjav/pass-update/commit/3fc36d8ae8964d3e5f803cc64dc19e48a0c76ad3)
