### ISSUE TITLE
mapfile: command not found

### ISSUE THREAD

**Issue by tpa0** [roddhjav/pass-update#29]
when I try to update several passwords with:
~ pass update -m test
says:
/usr/local/lib/password-store/extensions/update.bash: line 115: mapfile: command not found
find: -printf: unknown primary or operator

My computer is a MacOS, can anyone help?

**Comment by roddhjav** [comment]
You need to ensure bash is up to date. You need bash 5.x. See https://stackoverflow.com/questions/6047648/associative-arrays-error-declare-a-invalid-option

**Comment by tpa0** [comment]
Solved.

Had to change "find" for "gfind" on this file:
/usr/local/lib/password-store/extensions/update.bash
