### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by anarcat** [roddhjav/pass-update#32]
hello!

i see the last release of this project is from 2018, yet there are new commits up to 2022, including some improvements to tests and the makefile. To make a cleaner debian package (#31), it would be great to have a new upstream release.

Thanks!

**Comment by roddhjav** [comment]
I have released `pass-update` 2.2. Tell me if there is still an issue somewhere, I can release fix quickly.

**Comment by anarcat** [comment]
i think we can close this issue, since you did make a release (thanks!) but there's some issues with the debian package, which i documented in #31.
