### ISSUE TITLE
Update multiline pass?

### ISSUE THREAD

**Issue by c-jonua** [roddhjav/pass-update#4]
It would be cool if users could change a multilaned pass point. Also, if users could specify password by hand without generation. Can you do it in the next releases?

**Comment by roddhjav** [comment]
Yes, these are interesting feature, thank a lot for the proposal

**Comment by roddhjav** [comment]
Fixed with the latest changes. Tell me what you think. I will do a release soon.

**Comment by c-jonua** [comment]
I tested this feature, I think it works fine.
But, if I want to edit a multiline password, I want to edit all data, but not the first line only. For example, if I updates multiline pass, plugin could show data in default editor. What you think about this?

**Comment by c-jonua** [comment]
I tested this feature, basically it acceptable (for me) when plugin **replacing** data instead of update/edit them. But, if I (and somebody else, who like this plugin) gots the apportunity **edit** the data, I will be more happy. For example, if I updates multiline pass, plugin could show data in default editor. What you think about this?

**Comment by roddhjav** [comment]
If you want to edit the data why don't you use the `pass edit` command?

**Comment by c-jonua** [comment]
Hmm.. yes, you right. Then, issue was done, gret job, thanks @roddhjav :)

**Comment by roddhjav** [comment]
I added a `--edit`, `-e` option if someone needs it.
