### ISSUE TITLE
Tab completion?

### ISSUE THREAD

**Issue by benlindsay** [roddhjav/pass-update#9]
Is there any chance this supports tab completion? Tab completion works in my normal pass stuff, but not after I've typed `pass update ...`.

Thanks!

**Comment by benlindsay** [comment]
Nevermind, an issue in the tail extension explained how to add this. Kind of hacky but it seems like it has to be this way until pass adds direct support for tab completion for extensions? The issue is here: https://github.com/palortoff/pass-extension-tail/issues/4.

If anyone sees this in the future, on my mac the bash completion file was at `/usr/local/etc/bash_completion.d/pass`, and I changed line 84 to look like this:

    local commands="init ls find grep show insert generate edit rm mv cp git help version update tail tailedit"

(adding `update` for this plugin, and `tail` an `tailedit` for the other plugin)

and line 97 to look like this:

    ls|list|edit|update|tail|tailedit)

(same thing here).

**Comment by roddhjav** [comment]
Many thank for this information. I did the same kind of hacked completion for zsh. But right now, we need pass support to go further.

I'm reopening this issue because I plan to work on it in the future.

**Comment by benlindsay** [comment]
Also, mostly as just a note for future me, I had issues getting this hack to work properly on my mac unless bash and bash-completion were installed via homebrew, and my shell was running from `/usr/local/bin/bash` instead of `/bin/bash`

**Comment by roddhjav** [comment]
This is now natively supported by pass. There is the WIP implementation in #20

**Comment by roddhjav** [comment]
This is now implemented.

**Comment by NilsIrl** [comment]
For reference this was implemented in e81139302fd7597393e39e56742b00440482f4e4
